baseurl: ""
production_url: "http://awards.codeforamerica.org"
collections:
  judges:
    output: true
    permalink: /judges/:path/
  2015-winners:
    output: true
    permalink: /2015/winner/:path/

defaults:
  - scope:
      type: "judges"
    values:
      layout: "default"
      type: "judge"
  - scope:
      type: "2015-winners"
    values:
      layout: "default"
      type: "winner"
