baseurl: ""
production_url: "http://awards.codeforamerica.org"
collections:
  judges:
    output: true
    permalink: /judges/:path/

defaults:
  - scope:
      type: "judges"
    values:
      layout: "default"
      type: "judge"
      foo: "bar"